# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controller_api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='controller_api.proto',
  package='controller',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14\x63ontroller_api.proto\x12\ncontroller\"3\n\rOriginalImage\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63urrent_lat\x18\x02 \x01(\t\"2\n\x0b\x43ustomImage\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x14\n\x0c\x61\x63heived_acc\x18\x02 \x01(\t\"1\n\x07Targets\x12\x12\n\ntarget_lat\x18\x01 \x01(\t\x12\x12\n\ntarget_acc\x18\x02 \x01(\t\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\x90\x01\n\x11LatencyController\x12\x36\n\tSetTarget\x12\x13.controller.Targets\x1a\x12.controller.Status\"\x00\x12\x43\n\x07\x43ontrol\x12\x19.controller.OriginalImage\x1a\x17.controller.CustomImage\"\x00(\x01\x30\x01\x62\x06proto3')
)




_ORIGINALIMAGE = _descriptor.Descriptor(
  name='OriginalImage',
  full_name='controller.OriginalImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='controller.OriginalImage.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_lat', full_name='controller.OriginalImage.current_lat', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=87,
)


_CUSTOMIMAGE = _descriptor.Descriptor(
  name='CustomImage',
  full_name='controller.CustomImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='controller.CustomImage.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acheived_acc', full_name='controller.CustomImage.acheived_acc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=139,
)


_TARGETS = _descriptor.Descriptor(
  name='Targets',
  full_name='controller.Targets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_lat', full_name='controller.Targets.target_lat', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_acc', full_name='controller.Targets.target_acc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=190,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='controller.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='controller.Status.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=216,
)

DESCRIPTOR.message_types_by_name['OriginalImage'] = _ORIGINALIMAGE
DESCRIPTOR.message_types_by_name['CustomImage'] = _CUSTOMIMAGE
DESCRIPTOR.message_types_by_name['Targets'] = _TARGETS
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OriginalImage = _reflection.GeneratedProtocolMessageType('OriginalImage', (_message.Message,), dict(
  DESCRIPTOR = _ORIGINALIMAGE,
  __module__ = 'controller_api_pb2'
  # @@protoc_insertion_point(class_scope:controller.OriginalImage)
  ))
_sym_db.RegisterMessage(OriginalImage)

CustomImage = _reflection.GeneratedProtocolMessageType('CustomImage', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMIMAGE,
  __module__ = 'controller_api_pb2'
  # @@protoc_insertion_point(class_scope:controller.CustomImage)
  ))
_sym_db.RegisterMessage(CustomImage)

Targets = _reflection.GeneratedProtocolMessageType('Targets', (_message.Message,), dict(
  DESCRIPTOR = _TARGETS,
  __module__ = 'controller_api_pb2'
  # @@protoc_insertion_point(class_scope:controller.Targets)
  ))
_sym_db.RegisterMessage(Targets)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'controller_api_pb2'
  # @@protoc_insertion_point(class_scope:controller.Status)
  ))
_sym_db.RegisterMessage(Status)



_LATENCYCONTROLLER = _descriptor.ServiceDescriptor(
  name='LatencyController',
  full_name='controller.LatencyController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=219,
  serialized_end=363,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetTarget',
    full_name='controller.LatencyController.SetTarget',
    index=0,
    containing_service=None,
    input_type=_TARGETS,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Control',
    full_name='controller.LatencyController.Control',
    index=1,
    containing_service=None,
    input_type=_ORIGINALIMAGE,
    output_type=_CUSTOMIMAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LATENCYCONTROLLER)

DESCRIPTOR.services_by_name['LatencyController'] = _LATENCYCONTROLLER

# @@protoc_insertion_point(module_scope)
