// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/edgeserver/edgeserver_api.proto

package edgeserver

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Url struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Url) Reset()         { *m = Url{} }
func (m *Url) String() string { return proto.CompactTextString(m) }
func (*Url) ProtoMessage()    {}
func (*Url) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5e61ee460ad0a44, []int{0}
}

func (m *Url) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Url.Unmarshal(m, b)
}
func (m *Url) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Url.Marshal(b, m, deterministic)
}
func (m *Url) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Url.Merge(m, src)
}
func (m *Url) XXX_Size() int {
	return xxx_messageInfo_Url.Size(m)
}
func (m *Url) XXX_DiscardUnknown() {
	xxx_messageInfo_Url.DiscardUnknown(m)
}

var xxx_messageInfo_Url proto.InternalMessageInfo

func (m *Url) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Id struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5e61ee460ad0a44, []int{1}
}

func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (m *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(m, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Image struct {
	Image                []byte   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Timestamp            string   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5e61ee460ad0a44, []int{2}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Image) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type NodeInfo struct {
	Ipaddr               string   `protobuf:"bytes,1,opt,name=ipaddr,proto3" json:"ipaddr,omitempty"`
	Camid                string   `protobuf:"bytes,2,opt,name=camid,proto3" json:"camid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5e61ee460ad0a44, []int{3}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetIpaddr() string {
	if m != nil {
		return m.Ipaddr
	}
	return ""
}

func (m *NodeInfo) GetCamid() string {
	if m != nil {
		return m.Camid
	}
	return ""
}

type CameraParameters struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CameraParameters) Reset()         { *m = CameraParameters{} }
func (m *CameraParameters) String() string { return proto.CompactTextString(m) }
func (*CameraParameters) ProtoMessage()    {}
func (*CameraParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5e61ee460ad0a44, []int{4}
}

func (m *CameraParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CameraParameters.Unmarshal(m, b)
}
func (m *CameraParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CameraParameters.Marshal(b, m, deterministic)
}
func (m *CameraParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CameraParameters.Merge(m, src)
}
func (m *CameraParameters) XXX_Size() int {
	return xxx_messageInfo_CameraParameters.Size(m)
}
func (m *CameraParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_CameraParameters.DiscardUnknown(m)
}

var xxx_messageInfo_CameraParameters proto.InternalMessageInfo

type CameraInfo struct {
	Camid                []string `protobuf:"bytes,1,rep,name=camid,proto3" json:"camid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CameraInfo) Reset()         { *m = CameraInfo{} }
func (m *CameraInfo) String() string { return proto.CompactTextString(m) }
func (*CameraInfo) ProtoMessage()    {}
func (*CameraInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5e61ee460ad0a44, []int{5}
}

func (m *CameraInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CameraInfo.Unmarshal(m, b)
}
func (m *CameraInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CameraInfo.Marshal(b, m, deterministic)
}
func (m *CameraInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CameraInfo.Merge(m, src)
}
func (m *CameraInfo) XXX_Size() int {
	return xxx_messageInfo_CameraInfo.Size(m)
}
func (m *CameraInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CameraInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CameraInfo proto.InternalMessageInfo

func (m *CameraInfo) GetCamid() []string {
	if m != nil {
		return m.Camid
	}
	return nil
}

type ImageStreamParameters struct {
	Appid                string   `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Camid                string   `protobuf:"bytes,2,opt,name=camid,proto3" json:"camid,omitempty"`
	Latency              string   `protobuf:"bytes,3,opt,name=latency,proto3" json:"latency,omitempty"`
	Accuracy             string   `protobuf:"bytes,4,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Start                string   `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	Stop                 string   `protobuf:"bytes,6,opt,name=stop,proto3" json:"stop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageStreamParameters) Reset()         { *m = ImageStreamParameters{} }
func (m *ImageStreamParameters) String() string { return proto.CompactTextString(m) }
func (*ImageStreamParameters) ProtoMessage()    {}
func (*ImageStreamParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5e61ee460ad0a44, []int{6}
}

func (m *ImageStreamParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageStreamParameters.Unmarshal(m, b)
}
func (m *ImageStreamParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageStreamParameters.Marshal(b, m, deterministic)
}
func (m *ImageStreamParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageStreamParameters.Merge(m, src)
}
func (m *ImageStreamParameters) XXX_Size() int {
	return xxx_messageInfo_ImageStreamParameters.Size(m)
}
func (m *ImageStreamParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageStreamParameters.DiscardUnknown(m)
}

var xxx_messageInfo_ImageStreamParameters proto.InternalMessageInfo

func (m *ImageStreamParameters) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *ImageStreamParameters) GetCamid() string {
	if m != nil {
		return m.Camid
	}
	return ""
}

func (m *ImageStreamParameters) GetLatency() string {
	if m != nil {
		return m.Latency
	}
	return ""
}

func (m *ImageStreamParameters) GetAccuracy() string {
	if m != nil {
		return m.Accuracy
	}
	return ""
}

func (m *ImageStreamParameters) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *ImageStreamParameters) GetStop() string {
	if m != nil {
		return m.Stop
	}
	return ""
}

type AppInfo struct {
	Appid                string   `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Camid                string   `protobuf:"bytes,2,opt,name=camid,proto3" json:"camid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppInfo) Reset()         { *m = AppInfo{} }
func (m *AppInfo) String() string { return proto.CompactTextString(m) }
func (*AppInfo) ProtoMessage()    {}
func (*AppInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5e61ee460ad0a44, []int{7}
}

func (m *AppInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppInfo.Unmarshal(m, b)
}
func (m *AppInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppInfo.Marshal(b, m, deterministic)
}
func (m *AppInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppInfo.Merge(m, src)
}
func (m *AppInfo) XXX_Size() int {
	return xxx_messageInfo_AppInfo.Size(m)
}
func (m *AppInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AppInfo proto.InternalMessageInfo

func (m *AppInfo) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *AppInfo) GetCamid() string {
	if m != nil {
		return m.Camid
	}
	return ""
}

type Status struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5e61ee460ad0a44, []int{8}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*Url)(nil), "edgeserver.Url")
	proto.RegisterType((*Id)(nil), "edgeserver.Id")
	proto.RegisterType((*Image)(nil), "edgeserver.Image")
	proto.RegisterType((*NodeInfo)(nil), "edgeserver.NodeInfo")
	proto.RegisterType((*CameraParameters)(nil), "edgeserver.CameraParameters")
	proto.RegisterType((*CameraInfo)(nil), "edgeserver.CameraInfo")
	proto.RegisterType((*ImageStreamParameters)(nil), "edgeserver.ImageStreamParameters")
	proto.RegisterType((*AppInfo)(nil), "edgeserver.AppInfo")
	proto.RegisterType((*Status)(nil), "edgeserver.Status")
}

func init() {
	proto.RegisterFile("api/edgeserver/edgeserver_api.proto", fileDescriptor_a5e61ee460ad0a44)
}

var fileDescriptor_a5e61ee460ad0a44 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0x6e, 0xd2, 0x6b, 0xda, 0x8e, 0x7a, 0xea, 0x58, 0x8f, 0x10, 0x0e, 0xac, 0xeb, 0x8b, 0x0f,
	0x52, 0x45, 0x51, 0x0a, 0x3e, 0xc9, 0x21, 0x47, 0x5f, 0xe4, 0x68, 0xe9, 0xb3, 0x4c, 0xb2, 0x63,
	0x59, 0x68, 0x92, 0x65, 0x77, 0x23, 0xdc, 0xdf, 0xe3, 0x7f, 0xe8, 0x5f, 0x20, 0xd9, 0xa4, 0x4d,
	0xf4, 0xfa, 0x20, 0xf7, 0x36, 0xdf, 0x37, 0xf3, 0x7d, 0x99, 0x1f, 0x1b, 0x78, 0x45, 0x5a, 0xbd,
	0x65, 0xb9, 0x63, 0xcb, 0xe6, 0x27, 0x9b, 0x5e, 0xf8, 0x9d, 0xb4, 0x5a, 0x68, 0x53, 0xba, 0x12,
	0xa1, 0x63, 0xc5, 0x0b, 0x18, 0x6e, 0xcd, 0x1e, 0x63, 0x18, 0x93, 0x94, 0x86, 0xad, 0x8d, 0x83,
	0x79, 0xf0, 0x7a, 0xba, 0x3e, 0x40, 0x31, 0x83, 0x70, 0x25, 0xf1, 0x1c, 0x42, 0x25, 0xdb, 0x54,
	0xa8, 0xa4, 0xf8, 0x0c, 0xa3, 0x55, 0x4e, 0x3b, 0xc6, 0x19, 0x8c, 0x54, 0x1d, 0xf8, 0xdc, 0xc3,
	0x75, 0x03, 0xf0, 0x12, 0xa6, 0x4e, 0xe5, 0x6c, 0x1d, 0xe5, 0x3a, 0x0e, 0xbd, 0xaa, 0x23, 0xc4,
	0x12, 0x26, 0xdf, 0x4a, 0xc9, 0xab, 0xe2, 0x47, 0x89, 0x17, 0x10, 0x29, 0x5d, 0x7f, 0xab, 0x35,
	0x6f, 0x51, 0xed, 0x9b, 0x51, 0xae, 0x64, 0xab, 0x6e, 0x80, 0x40, 0x78, 0x72, 0x45, 0x39, 0x1b,
	0xba, 0x21, 0x43, 0x39, 0x3b, 0x36, 0x56, 0x08, 0x80, 0x86, 0xf3, 0x7e, 0x47, 0x5d, 0x30, 0x1f,
	0x76, 0xba, 0x5f, 0x01, 0x3c, 0xf7, 0xfd, 0x6e, 0x9c, 0x61, 0xca, 0x3b, 0x75, 0x5d, 0x4f, 0x5a,
	0x1f, 0x67, 0x6b, 0xc0, 0xe9, 0xaf, 0xd7, 0x4b, 0xda, 0x93, 0xe3, 0x22, 0xbb, 0x8d, 0x87, 0xcd,
	0x92, 0x5a, 0x88, 0x09, 0x4c, 0x28, 0xcb, 0x2a, 0x43, 0xd9, 0x6d, 0x7c, 0xe6, 0x53, 0x47, 0x5c,
	0x7b, 0x59, 0x47, 0xc6, 0xc5, 0xa3, 0xc6, 0xcb, 0x03, 0x44, 0x38, 0xb3, 0xae, 0xd4, 0x71, 0xe4,
	0x49, 0x1f, 0x8b, 0x8f, 0x30, 0xfe, 0xa2, 0xf5, 0x61, 0x8c, 0xff, 0x6d, 0x4b, 0xcc, 0x21, 0xda,
	0x38, 0x72, 0x95, 0xad, 0x97, 0x69, 0x7d, 0xe4, 0x65, 0x93, 0x75, 0x8b, 0xde, 0xff, 0x0e, 0x21,
	0xba, 0xa9, 0xd2, 0x4d, 0x95, 0xe2, 0x1b, 0x18, 0x5f, 0x95, 0x45, 0xc1, 0x99, 0xc3, 0xc7, 0x8b,
	0xee, 0x1d, 0x2c, 0xb6, 0x66, 0x9f, 0x9c, 0xf7, 0x89, 0x95, 0x14, 0x03, 0xfc, 0x04, 0x93, 0x35,
	0xef, 0x94, 0x75, 0x6c, 0x70, 0xd6, 0xcf, 0x1e, 0xee, 0x97, 0x60, 0x9f, 0x6d, 0xda, 0x10, 0x03,
	0x5c, 0x02, 0x6c, 0x0b, 0x73, 0x1f, 0xe5, 0x35, 0x3c, 0xba, 0x66, 0xd7, 0x3b, 0xe8, 0x65, 0xbf,
	0xec, 0xdf, 0xe3, 0x27, 0x17, 0x77, 0xb3, 0xb5, 0x4a, 0x0c, 0xf0, 0x2b, 0x4c, 0x37, 0x55, 0x6a,
	0x33, 0xa3, 0x52, 0xc6, 0x97, 0x7f, 0x4d, 0x76, 0xea, 0x21, 0x24, 0x4f, 0xef, 0x94, 0x88, 0xc1,
	0xbb, 0x00, 0x97, 0xf0, 0x60, 0x5b, 0xd8, 0xa3, 0xd1, 0xb3, 0x7e, 0x55, 0x7b, 0xac, 0xd3, 0x93,
	0xa4, 0x91, 0xff, 0xd9, 0x3e, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0x35, 0x3d, 0xda, 0x1b, 0x93,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PubSubClient is the client API for PubSub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PubSubClient interface {
	Connect(ctx context.Context, in *Url, opts ...grpc.CallOption) (*Id, error)
	Register(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*Status, error)
	Unregister(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*Status, error)
	GetCameraInfo(ctx context.Context, in *CameraParameters, opts ...grpc.CallOption) (*CameraInfo, error)
	Subscribe(ctx context.Context, in *ImageStreamParameters, opts ...grpc.CallOption) (PubSub_SubscribeClient, error)
	Unsubscribe(ctx context.Context, in *AppInfo, opts ...grpc.CallOption) (*Status, error)
}

type pubSubClient struct {
	cc *grpc.ClientConn
}

func NewPubSubClient(cc *grpc.ClientConn) PubSubClient {
	return &pubSubClient{cc}
}

func (c *pubSubClient) Connect(ctx context.Context, in *Url, opts ...grpc.CallOption) (*Id, error) {
	out := new(Id)
	err := c.cc.Invoke(ctx, "/edgeserver.PubSub/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubClient) Register(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/edgeserver.PubSub/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubClient) Unregister(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/edgeserver.PubSub/Unregister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubClient) GetCameraInfo(ctx context.Context, in *CameraParameters, opts ...grpc.CallOption) (*CameraInfo, error) {
	out := new(CameraInfo)
	err := c.cc.Invoke(ctx, "/edgeserver.PubSub/GetCameraInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pubSubClient) Subscribe(ctx context.Context, in *ImageStreamParameters, opts ...grpc.CallOption) (PubSub_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PubSub_serviceDesc.Streams[0], "/edgeserver.PubSub/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &pubSubSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PubSub_SubscribeClient interface {
	Recv() (*Image, error)
	grpc.ClientStream
}

type pubSubSubscribeClient struct {
	grpc.ClientStream
}

func (x *pubSubSubscribeClient) Recv() (*Image, error) {
	m := new(Image)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pubSubClient) Unsubscribe(ctx context.Context, in *AppInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/edgeserver.PubSub/Unsubscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PubSubServer is the server API for PubSub service.
type PubSubServer interface {
	Connect(context.Context, *Url) (*Id, error)
	Register(context.Context, *NodeInfo) (*Status, error)
	Unregister(context.Context, *NodeInfo) (*Status, error)
	GetCameraInfo(context.Context, *CameraParameters) (*CameraInfo, error)
	Subscribe(*ImageStreamParameters, PubSub_SubscribeServer) error
	Unsubscribe(context.Context, *AppInfo) (*Status, error)
}

func RegisterPubSubServer(s *grpc.Server, srv PubSubServer) {
	s.RegisterService(&_PubSub_serviceDesc, srv)
}

func _PubSub_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Url)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edgeserver.PubSub/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServer).Connect(ctx, req.(*Url))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSub_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edgeserver.PubSub/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServer).Register(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSub_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edgeserver.PubSub/Unregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServer).Unregister(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSub_GetCameraInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CameraParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServer).GetCameraInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edgeserver.PubSub/GetCameraInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServer).GetCameraInfo(ctx, req.(*CameraParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _PubSub_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ImageStreamParameters)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PubSubServer).Subscribe(m, &pubSubSubscribeServer{stream})
}

type PubSub_SubscribeServer interface {
	Send(*Image) error
	grpc.ServerStream
}

type pubSubSubscribeServer struct {
	grpc.ServerStream
}

func (x *pubSubSubscribeServer) Send(m *Image) error {
	return x.ServerStream.SendMsg(m)
}

func _PubSub_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edgeserver.PubSub/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServer).Unsubscribe(ctx, req.(*AppInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _PubSub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "edgeserver.PubSub",
	HandlerType: (*PubSubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _PubSub_Connect_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _PubSub_Register_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _PubSub_Unregister_Handler,
		},
		{
			MethodName: "GetCameraInfo",
			Handler:    _PubSub_GetCameraInfo_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _PubSub_Unsubscribe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _PubSub_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/edgeserver/edgeserver_api.proto",
}
