// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storagepb/storagepb.proto

package storagepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BFileItem struct {
	Img                  []byte               `protobuf:"bytes,1,opt,name=Img,proto3" json:"Img,omitempty"`
	Ts                   *timestamp.Timestamp `protobuf:"bytes,2,opt,name=Ts,proto3" json:"Ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BFileItem) Reset()         { *m = BFileItem{} }
func (m *BFileItem) String() string { return proto.CompactTextString(m) }
func (*BFileItem) ProtoMessage()    {}
func (*BFileItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_854ce5936a0ea2b8, []int{0}
}

func (m *BFileItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BFileItem.Unmarshal(m, b)
}
func (m *BFileItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BFileItem.Marshal(b, m, deterministic)
}
func (m *BFileItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BFileItem.Merge(m, src)
}
func (m *BFileItem) XXX_Size() int {
	return xxx_messageInfo_BFileItem.Size(m)
}
func (m *BFileItem) XXX_DiscardUnknown() {
	xxx_messageInfo_BFileItem.DiscardUnknown(m)
}

var xxx_messageInfo_BFileItem proto.InternalMessageInfo

func (m *BFileItem) GetImg() []byte {
	if m != nil {
		return m.Img
	}
	return nil
}

func (m *BFileItem) GetTs() *timestamp.Timestamp {
	if m != nil {
		return m.Ts
	}
	return nil
}

type BFileItemArray struct {
	BItems               []*BFileItem `protobuf:"bytes,1,rep,name=BItems,proto3" json:"BItems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BFileItemArray) Reset()         { *m = BFileItemArray{} }
func (m *BFileItemArray) String() string { return proto.CompactTextString(m) }
func (*BFileItemArray) ProtoMessage()    {}
func (*BFileItemArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_854ce5936a0ea2b8, []int{1}
}

func (m *BFileItemArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BFileItemArray.Unmarshal(m, b)
}
func (m *BFileItemArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BFileItemArray.Marshal(b, m, deterministic)
}
func (m *BFileItemArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BFileItemArray.Merge(m, src)
}
func (m *BFileItemArray) XXX_Size() int {
	return xxx_messageInfo_BFileItemArray.Size(m)
}
func (m *BFileItemArray) XXX_DiscardUnknown() {
	xxx_messageInfo_BFileItemArray.DiscardUnknown(m)
}

var xxx_messageInfo_BFileItemArray proto.InternalMessageInfo

func (m *BFileItemArray) GetBItems() []*BFileItem {
	if m != nil {
		return m.BItems
	}
	return nil
}

func init() {
	proto.RegisterType((*BFileItem)(nil), "storagepb.BFileItem")
	proto.RegisterType((*BFileItemArray)(nil), "storagepb.BFileItemArray")
}

func init() { proto.RegisterFile("storagepb/storagepb.proto", fileDescriptor_854ce5936a0ea2b8) }

var fileDescriptor_854ce5936a0ea2b8 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x2e, 0xc9, 0x2f,
	0x4a, 0x4c, 0x4f, 0x2d, 0x48, 0xd2, 0x87, 0xb3, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38,
	0xe1, 0x02, 0x52, 0xf2, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x60, 0x89, 0xa4, 0xd2, 0x34,
	0xfd, 0x92, 0xcc, 0xdc, 0xd4, 0xe2, 0x92, 0xc4, 0xdc, 0x02, 0x88, 0x5a, 0x25, 0x4f, 0x2e, 0x4e,
	0x27, 0xb7, 0xcc, 0x9c, 0x54, 0xcf, 0x92, 0xd4, 0x5c, 0x21, 0x01, 0x2e, 0x66, 0xcf, 0xdc, 0x74,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x10, 0x53, 0x48, 0x8b, 0x8b, 0x29, 0xa4, 0x58, 0x82,
	0x49, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x4a, 0x0f, 0x62, 0x98, 0x1e, 0xcc, 0x30, 0xbd, 0x10, 0x98,
	0x61, 0x41, 0x4c, 0x21, 0xc5, 0x4a, 0x76, 0x5c, 0x7c, 0x70, 0xa3, 0x1c, 0x8b, 0x8a, 0x12, 0x2b,
	0x85, 0x74, 0xb8, 0xd8, 0x9c, 0x40, 0xbc, 0x62, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x11,
	0x3d, 0x84, 0x53, 0xe1, 0x4a, 0x83, 0xa0, 0x6a, 0x92, 0xd8, 0xc0, 0xe6, 0x1a, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x57, 0xcd, 0x2e, 0x71, 0xda, 0x00, 0x00, 0x00,
}
