// Code generated by protoc-gen-go. DO NOT EDIT.
// source: edgenode_api.proto

package edgenode

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Image struct {
	Image                []byte   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Timestamp            string   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_447eaeabb5bfdb36, []int{0}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Image) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type CameraInfo struct {
	Camid                []string `protobuf:"bytes,1,rep,name=camid,proto3" json:"camid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CameraInfo) Reset()         { *m = CameraInfo{} }
func (m *CameraInfo) String() string { return proto.CompactTextString(m) }
func (*CameraInfo) ProtoMessage()    {}
func (*CameraInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_447eaeabb5bfdb36, []int{1}
}

func (m *CameraInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CameraInfo.Unmarshal(m, b)
}
func (m *CameraInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CameraInfo.Marshal(b, m, deterministic)
}
func (m *CameraInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CameraInfo.Merge(m, src)
}
func (m *CameraInfo) XXX_Size() int {
	return xxx_messageInfo_CameraInfo.Size(m)
}
func (m *CameraInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CameraInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CameraInfo proto.InternalMessageInfo

func (m *CameraInfo) GetCamid() []string {
	if m != nil {
		return m.Camid
	}
	return nil
}

type ImageStreamParameters struct {
	Camid                string   `protobuf:"bytes,1,opt,name=camid,proto3" json:"camid,omitempty"`
	Latency              string   `protobuf:"bytes,2,opt,name=latency,proto3" json:"latency,omitempty"`
	Accuracy             string   `protobuf:"bytes,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Start                string   `protobuf:"bytes,4,opt,name=start,proto3" json:"start,omitempty"`
	Stop                 string   `protobuf:"bytes,5,opt,name=stop,proto3" json:"stop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageStreamParameters) Reset()         { *m = ImageStreamParameters{} }
func (m *ImageStreamParameters) String() string { return proto.CompactTextString(m) }
func (*ImageStreamParameters) ProtoMessage()    {}
func (*ImageStreamParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_447eaeabb5bfdb36, []int{2}
}

func (m *ImageStreamParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageStreamParameters.Unmarshal(m, b)
}
func (m *ImageStreamParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageStreamParameters.Marshal(b, m, deterministic)
}
func (m *ImageStreamParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageStreamParameters.Merge(m, src)
}
func (m *ImageStreamParameters) XXX_Size() int {
	return xxx_messageInfo_ImageStreamParameters.Size(m)
}
func (m *ImageStreamParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageStreamParameters.DiscardUnknown(m)
}

var xxx_messageInfo_ImageStreamParameters proto.InternalMessageInfo

func (m *ImageStreamParameters) GetCamid() string {
	if m != nil {
		return m.Camid
	}
	return ""
}

func (m *ImageStreamParameters) GetLatency() string {
	if m != nil {
		return m.Latency
	}
	return ""
}

func (m *ImageStreamParameters) GetAccuracy() string {
	if m != nil {
		return m.Accuracy
	}
	return ""
}

func (m *ImageStreamParameters) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *ImageStreamParameters) GetStop() string {
	if m != nil {
		return m.Stop
	}
	return ""
}

type Status struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_447eaeabb5bfdb36, []int{3}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*Image)(nil), "edgenode.Image")
	proto.RegisterType((*CameraInfo)(nil), "edgenode.CameraInfo")
	proto.RegisterType((*ImageStreamParameters)(nil), "edgenode.ImageStreamParameters")
	proto.RegisterType((*Status)(nil), "edgenode.Status")
}

func init() { proto.RegisterFile("edgenode_api.proto", fileDescriptor_447eaeabb5bfdb36) }

var fileDescriptor_447eaeabb5bfdb36 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0x87, 0xbb, 0xb6, 0x4d, 0x9b, 0x51, 0x50, 0x86, 0x2a, 0x4b, 0x11, 0x0c, 0x7b, 0xca, 0xa9,
	0x14, 0x3d, 0x78, 0xf0, 0x24, 0x9e, 0x7a, 0x2b, 0x09, 0x9e, 0x65, 0x92, 0xae, 0x75, 0xa1, 0x9b,
	0x84, 0xfd, 0x73, 0xe8, 0x43, 0xf8, 0x3a, 0x3e, 0x9f, 0x74, 0xd3, 0x36, 0x12, 0xbc, 0xcd, 0xf7,
	0xcb, 0xe4, 0x9b, 0xdd, 0x59, 0x40, 0xb9, 0xd9, 0xca, 0xaa, 0xde, 0xc8, 0x0f, 0x6a, 0xd4, 0xa2,
	0x31, 0xb5, 0xab, 0x71, 0x7a, 0xca, 0xc4, 0x0b, 0x8c, 0x57, 0x9a, 0xb6, 0x12, 0x67, 0x30, 0x56,
	0x87, 0x82, 0xb3, 0x84, 0xa5, 0x57, 0x59, 0x0b, 0x78, 0x0f, 0xb1, 0x53, 0x5a, 0x5a, 0x47, 0xba,
	0xe1, 0x17, 0x09, 0x4b, 0xe3, 0xac, 0x0b, 0x84, 0x00, 0x78, 0x23, 0x2d, 0x0d, 0xad, 0xaa, 0xcf,
	0xfa, 0x60, 0x28, 0x49, 0xab, 0x0d, 0x67, 0xc9, 0x30, 0x8d, 0xb3, 0x16, 0xc4, 0x37, 0x83, 0xdb,
	0x30, 0x21, 0x77, 0x46, 0x92, 0x5e, 0x93, 0x21, 0x2d, 0x9d, 0x34, 0xf6, 0x6f, 0x3f, 0x3b, 0xf7,
	0x23, 0x87, 0xc9, 0x8e, 0x9c, 0xac, 0xca, 0xfd, 0x71, 0xde, 0x09, 0x71, 0x0e, 0x53, 0x2a, 0x4b,
	0x6f, 0xa8, 0xdc, 0xf3, 0x61, 0xf8, 0x74, 0xe6, 0x83, 0xcb, 0x3a, 0x32, 0x8e, 0x8f, 0x5a, 0x57,
	0x00, 0x44, 0x18, 0x59, 0x57, 0x37, 0x7c, 0x1c, 0xc2, 0x50, 0x8b, 0x04, 0xa2, 0xdc, 0x91, 0xf3,
	0x16, 0xef, 0x20, 0xb2, 0xa1, 0x0a, 0x07, 0x98, 0x66, 0x47, 0x7a, 0xfc, 0x61, 0x10, 0xad, 0x7d,
	0x91, 0xfb, 0x02, 0x97, 0x30, 0x59, 0xfb, 0x62, 0xa7, 0xec, 0x17, 0x5e, 0x2f, 0x4e, 0x3b, 0x5b,
	0x84, 0xeb, 0xcc, 0x6f, 0xba, 0xa0, 0x15, 0x8a, 0x41, 0xca, 0xf0, 0x15, 0xe2, 0xdc, 0x17, 0xb6,
	0x34, 0xaa, 0x90, 0xf8, 0xd0, 0xfb, 0xa7, 0xbf, 0x82, 0x79, 0x5f, 0x2a, 0x06, 0x4b, 0x86, 0xcf,
	0x70, 0xf9, 0x5e, 0xd9, 0xb3, 0x64, 0xd6, 0xf5, 0x74, 0xcb, 0xfe, 0x6f, 0x7a, 0x11, 0x85, 0xc7,
	0x7d, 0xfa, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x01, 0xc3, 0x86, 0x52, 0xf2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PubSubClient is the client API for PubSub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PubSubClient interface {
	Publish(ctx context.Context, opts ...grpc.CallOption) (PubSub_PublishClient, error)
	Subscribe(ctx context.Context, in *ImageStreamParameters, opts ...grpc.CallOption) (PubSub_SubscribeClient, error)
	Unsubscribe(ctx context.Context, in *CameraInfo, opts ...grpc.CallOption) (*Status, error)
}

type pubSubClient struct {
	cc *grpc.ClientConn
}

func NewPubSubClient(cc *grpc.ClientConn) PubSubClient {
	return &pubSubClient{cc}
}

func (c *pubSubClient) Publish(ctx context.Context, opts ...grpc.CallOption) (PubSub_PublishClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PubSub_serviceDesc.Streams[0], "/edgenode.PubSub/Publish", opts...)
	if err != nil {
		return nil, err
	}
	x := &pubSubPublishClient{stream}
	return x, nil
}

type PubSub_PublishClient interface {
	Send(*Image) error
	CloseAndRecv() (*Status, error)
	grpc.ClientStream
}

type pubSubPublishClient struct {
	grpc.ClientStream
}

func (x *pubSubPublishClient) Send(m *Image) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pubSubPublishClient) CloseAndRecv() (*Status, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Status)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pubSubClient) Subscribe(ctx context.Context, in *ImageStreamParameters, opts ...grpc.CallOption) (PubSub_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PubSub_serviceDesc.Streams[1], "/edgenode.PubSub/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &pubSubSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PubSub_SubscribeClient interface {
	Recv() (*Image, error)
	grpc.ClientStream
}

type pubSubSubscribeClient struct {
	grpc.ClientStream
}

func (x *pubSubSubscribeClient) Recv() (*Image, error) {
	m := new(Image)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pubSubClient) Unsubscribe(ctx context.Context, in *CameraInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/edgenode.PubSub/Unsubscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PubSubServer is the server API for PubSub service.
type PubSubServer interface {
	Publish(PubSub_PublishServer) error
	Subscribe(*ImageStreamParameters, PubSub_SubscribeServer) error
	Unsubscribe(context.Context, *CameraInfo) (*Status, error)
}

// UnimplementedPubSubServer can be embedded to have forward compatible implementations.
type UnimplementedPubSubServer struct {
}

func (*UnimplementedPubSubServer) Publish(srv PubSub_PublishServer) error {
	return status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (*UnimplementedPubSubServer) Subscribe(req *ImageStreamParameters, srv PubSub_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (*UnimplementedPubSubServer) Unsubscribe(ctx context.Context, req *CameraInfo) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsubscribe not implemented")
}

func RegisterPubSubServer(s *grpc.Server, srv PubSubServer) {
	s.RegisterService(&_PubSub_serviceDesc, srv)
}

func _PubSub_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PubSubServer).Publish(&pubSubPublishServer{stream})
}

type PubSub_PublishServer interface {
	SendAndClose(*Status) error
	Recv() (*Image, error)
	grpc.ServerStream
}

type pubSubPublishServer struct {
	grpc.ServerStream
}

func (x *pubSubPublishServer) SendAndClose(m *Status) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pubSubPublishServer) Recv() (*Image, error) {
	m := new(Image)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PubSub_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ImageStreamParameters)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PubSubServer).Subscribe(m, &pubSubSubscribeServer{stream})
}

type PubSub_SubscribeServer interface {
	Send(*Image) error
	grpc.ServerStream
}

type pubSubSubscribeServer struct {
	grpc.ServerStream
}

func (x *pubSubSubscribeServer) Send(m *Image) error {
	return x.ServerStream.SendMsg(m)
}

func _PubSub_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CameraInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubSubServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edgenode.PubSub/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubSubServer).Unsubscribe(ctx, req.(*CameraInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _PubSub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "edgenode.PubSub",
	HandlerType: (*PubSubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unsubscribe",
			Handler:    _PubSub_Unsubscribe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _PubSub_Publish_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _PubSub_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "edgenode_api.proto",
}
